import { LegalPage } from '../components/LegalPage'

/**
 * Aria Privacy Policy — version 1.0.
 * Placeholders to finalize before launch: {{OPERATOR_NAME}}, {{CONTACT_EMAIL}}, the Federal Republic of Nigeria.
 */
export const PrivacyPolicy = () => (
  <LegalPage title="Privacy Policy" lastUpdated="July 29, 2026" version="1.0">
    <p>
      Aria is a place people bring their honest thoughts — their faith, their doubts, their
      hard days. We think that deserves a privacy policy written in plain language, not
      legalese. This document explains what we collect, who sees it, and the control you have.
    </p>

    <div className="legal-note">
      <p>
        <strong>The short version:</strong> we collect your account details and the conversations
        you have with Aria. Those conversations are processed by AI providers in order to answer
        you — please don&apos;t share identifying details like your full address or ID numbers.
        We never sell your data or use it for advertising. You can clear Aria&apos;s memory of you
        at any time, and you can ask us to delete your account entirely.
      </p>
    </div>

    <h2>1. Who we are</h2>
    <p>
      Aria (&quot;Aria&quot;, &quot;we&quot;, &quot;us&quot;) is operated by the Aria team.
      Questions about this policy or your data: <strong>{'{{CONTACT_EMAIL}}'}</strong>.
    </p>

    <h2>2. What we collect</h2>
    <h3>Account information</h3>
    <p>
      Your name, email address, and profile image if you add one. Authentication (sign-in,
      password storage, &quot;Sign in with Google&quot;) is handled by Supabase, which stores your
      credentials securely on our behalf.
    </p>
    <h3>Conversations and content you create</h3>
    <ul>
      <li>AI chat messages, Bible study sessions, emotional support sessions, and devotion conversations</li>
      <li>Journal entries, notes (including password-locked notes), saved prayers, and favorites</li>
      <li>Your preferences — for example your chosen voice and Bible translation</li>
    </ul>
    <h3>Voice calls</h3>
    <p>
      When you call Aria, audio is streamed in real time to generate her spoken responses.
      After a call, we store a written summary of the conversation so Aria can remember your
      journey between sessions. You can erase this memory at any time from your Profile
      (&quot;Clear Memory&quot;).
    </p>
    <h3>Technical information</h3>
    <p>
      Standard server logs (such as request timestamps and error reports) that keep the app
      running and help us fix problems. If error monitoring (Sentry) is enabled, crash
      diagnostics may be sent to it — never the content of your private conversations
      as a practice, though error context can include limited technical metadata.
    </p>

    <h2>3. The honest part: AI providers see your conversations</h2>
    <p>
      Aria&apos;s responses are generated by third-party AI services. To answer you, the text of
      your messages — and audio during voice calls — is sent to these providers. They currently
      include <strong>OpenAI</strong>, <strong>NVIDIA</strong>, and <strong>Hugging Face</strong>,
      and may include <strong>Google</strong> or <strong>Alibaba Cloud</strong> for premium voice
      features. Each provider processes your content under its own terms in order to return a
      response to us.
    </p>
    <div className="legal-note">
      <p>
        <strong>Please be mindful:</strong> conversations with Aria can involve religious belief
        and emotional health, which are sensitive categories of personal data. Because message
        content is processed by AI providers, we recommend you <strong>do not include direct
        identifiers</strong> (full legal names of others, ID numbers, exact addresses, financial
        details) in your conversations.
      </p>
    </div>

    <h2>4. Infrastructure providers</h2>
    <ul>
      <li><strong>Supabase</strong> — authentication and database hosting</li>
      <li><strong>Upstash</strong> — caching (Redis) to make the app faster</li>
      <li><strong>Render</strong> — application hosting</li>
      <li><strong>Paystack</strong> — payment processing, if and when you purchase premium minutes (we never see or store your card details)</li>
    </ul>
    <p>
      These providers process data on our behalf under their respective data-processing terms.
      Your data is stored and processed in regions including the United States. If you use Aria
      from outside those regions (for example Nigeria or the EU), using Aria means you consent to
      these transfers, which are protected by the providers&apos; standard contractual safeguards.
    </p>

    <h2>5. What we never do</h2>
    <ul>
      <li>We never sell your personal data.</li>
      <li>We never use your conversations for advertising.</li>
      <li>We never train AI models on your private content.</li>
    </ul>

    <h2>6. Your control over your data</h2>
    <ul>
      <li><strong>Aria&apos;s memory of you:</strong> clear it anytime via Profile → Clear Memory.</li>
      <li><strong>Notes and journals:</strong> delete them yourself from within the app.</li>
      <li><strong>Everything else:</strong> email us at {'{{CONTACT_EMAIL}}'} and we will provide,
        correct, or delete your personal data, normally within 30 days.</li>
    </ul>

    <h2>7. Security</h2>
    <p>
      Connections are encrypted in transit (HTTPS/WSS). Passwords are hashed by Supabase and are
      never visible to us. Access to production systems is limited to the Aria team. No system is
      perfectly secure — if a breach ever affected your data, we would notify you promptly.
    </p>

    <h2>8. Children</h2>
    <p>
      Aria is not intended for children under 13. We do not knowingly collect data from them; if
      we learn we have, we will delete it.
    </p>

    <h2>9. Changes to this policy</h2>
    <p>
      When we make material changes, we will present the updated policy for your acceptance and
      record the version you agreed to. The version number and date at the top of this page
      always reflect the current edition.
    </p>

    <h2>10. Contact</h2>
    <p>
      Anything unclear, or a request about your data: <strong>{'{{CONTACT_EMAIL}}'}</strong>.
      Governed under the laws of {'the Federal Republic of Nigeria'}.
    </p>
  </LegalPage>
)

export default PrivacyPolicy
